#!/usr/bin/env bash

PICTURE=$HOME/.config/i3/images/Group\ 2pin.png
# SCREENSHOT="scrot -z $PICTURE"

# BLUR="5x4"

# $SCREENSHOT
# convert $PICTURE -blur $BLUR $PICTURE
i3lock -t -i $PICTURE
# rm $PICTURE
